### ISSUE TITLE
TR Windows version does not jump to search results but display 'cannot find'.

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#114]
![image](https://user-images.githubusercontent.com/111456572/195136445-697e9068-1b12-4eb9-af75-fd4da023081e.png)

![image](https://user-images.githubusercontent.com/111456572/195136527-d5963134-6e30-435a-bff8-48275f3147d7.png)

**Comment by bksubhuti** [comment]
He is using Windows build from store.  Not reproducible in Linux Desktop (maybe fixed)  will check windows soon.

**Comment by bksubhuti** [comment]
fixed with latest release:  Closed
