### ISSUE TITLE
Search filter 

### ISSUE THREAD

**Issue by Kapilawansa** [bksubhuti/tipitaka-pali-reader#115]
(1) I'm using TPR 1.1.5  and search filter resets to select all books after each search and need to set it every time to omit results of irrelevant books. That is a problem and search filter is better to have saved after once manually selected books. 
(2) There're some search results showing only the number of word and then can't find. 
(3) Also some search results are not highlighted. 
(4) If you could implement, I have a suggestion for the search option to have 4 steps as in CSP app. Because when insert a word in search box it shows the variants of same word to select one. Then TPR shows all results one by one at once and it mght be 50 or 100 or more than 100 results have to scroll through, which makes it hard long scrolling to find somewhere. In CSP search, the second step is as bookwise result. Then it can easily pick a book exactly where is looking up. I think you may understand the complexity of bypassing bookwise result in TPR. Showing "bookwise search results" at second step in CSP save the time and make easy to find in relevant areas.

**Comment by bksubhuti** [comment]
Please retry on the latest build.. released yesterday and today.

**Comment by Kapilawansa** [comment]
Still filter resets to select all itself after setit manually in version 1.1.6.

**Comment by bksubhuti** [comment]
Please create a new issue for each problem. Please include screen shots.
Exact examples of what you did to reproduce this.

The persistence of filter is already an issue
https://github.com/bksubhuti/tipitaka-pali-reader/issues/92
No need to make that a separate issue

**Comment by bksubhuti** [comment]
Please create an issue for #2 and 3
Search filter persistence is finished and in the release coming this next week.
