### ISSUE TITLE
To change icon shape on Mac

### ISSUE THREAD

**Issue by Nandavamsa** [bksubhuti/tipitaka-pali-reader#119]
Thanks for this App.
I want that to redesign App of icon on Mac. Current icon is not the same shape as other icon because it's too square corners. If you redesign for it like iPad iPhone 'Tipitaka Pali reader' apps shape, there would be better.
With loving kindness Nandavamsa.

**Comment by bksubhuti** [comment]
can you make an apple icon for us if we give you the original?

**Comment by Nandavamsa** [comment]
I think I can do it. Please send it to my email ***@***.*** ***@***.***>.
I will try it.

**Comment by bksubhuti** [comment]
I cannot see your email.  But you can drop the new icon here.
Right click on the icon and download.


![icon](https://user-images.githubusercontent.com/18184280/199226300-15eb67e4-ea55-4ef8-b269-2e54496b1585.png)

**Comment by Nandavamsa** [comment]
Ok, thanks.

**Comment by Nandavamsa** [comment]
![16pt_1x](https://user-images.githubusercontent.com/115969802/199939636-c74a8b81-9e3f-4f48-b74b-1e8cb1df79fb.png)
![16pt_2x](https://user-images.githubusercontent.com/115969802/199939646-3021a25e-f2e0-4c8e-9486-02b2692875d9.png)
![32pt_1x](https://user-images.githubusercontent.com/115969802/199939653-63565478-0619-4ac7-9350-7f42440abc50.png)
![32pt_2x](https://user-images.githubusercontent.com/115969802/199939657-64179c8d-c3b0-4828-b71f-409bd1c86c99.png)
![64pt_1x](https://user-images.githubusercontent.com/115969802/199939666-b0dae2f3-ad68-4eac-90a0-8613c51f179b.png)
![64pt_2x](https://user-images.githubusercontent.com/115969802/199939668-04e78e2e-01dd-43bd-abf5-7e390707f6d2.png)
![128pt_1x](https://user-images.githubusercontent.com/115969802/199939671-80e2a22a-fa08-44e8-9450-32f02590e9ad.png)
![128pt_2x](https://user-images.githubusercontent.com/115969802/199939678-08725d12-5944-4a9f-98e9-34547ba57e75.png)
![256pt_1x](https://user-images.githubusercontent.com/115969802/199939685-35ea6bab-96dd-4ba8-a5a4-4846e74b8b87.png)
![256pt_2x](https://user-images.githubusercontent.com/115969802/199939689-36eefed8-b9b9-4ed8-a1ed-e56460eae239.png)
![512pt_1x](https://user-images.githubusercontent.com/115969802/199939695-7cb7f4c8-b614-4d0d-b078-6a83a633908f.png)
![512pt_2x](https://user-images.githubusercontent.com/115969802/199939705-043c71de-fa2e-410c-bf7b-fbd99582e01c.png)
![1024pt](https://user-images.githubusercontent.com/115969802/199939720-3af807e0-75fb-42a8-a8db-f33714f94858.png)

I hope all of these icon images are working on MacOS.
May you be peaceful 'Bante'.🙏

**Comment by tharindu** [comment]
Submitted the macOS app for Apple's review. 🙏 
Version 2.1.1 (16)

**Comment by bksubhuti** [comment]
fixed and tested (by Tharindu)
