### ISSUE TITLE
Filter selection resets itself after each search.

### ISSUE THREAD

**Issue by Kapilawansa** [bksubhuti/tipitaka-pali-reader#120]
**Describe the bug**
Filter resets itself after each search. 

**To Reproduce**
1. Go to search.
2. Type a pali word.
3. Set the filter by selecting some books and lookup results.
4. Go back to search another word.
5. Check the filter selection again and it has reset itself to select all books.

**Expected behavior**
Filter selection should be saved after  setting it once manually. Otherwise need to set it for each search if it resets itself to select all books after each search. 
**Screenshots**

**Smartphone:**
 - Device: Vivo v11pro
 - OS: android 
 - Version 8.1

**Additional context**
Selecting books for search filter should be done by manually. Resting filter selection itself after each search is a problem.

**Comment by bksubhuti** [comment]
we know about this.  We are uncertain when it will be fixed.. maybe for November release.  Sadhu for your input

**Comment by bksubhuti** [comment]
fixed.. will be in the next release (maybe this month)
