### ISSUE TITLE
White blanks

### ISSUE THREAD

**Issue by PhiRunh** [bksubhuti/tipitaka-pali-reader#123]
When switchin to Khmer font, many white blanks appear.
![Screenshot_20221027_124942_com paauk tipitakapalireader](https://user-images.githubusercontent.com/79864488/198203902-3df0f0ed-51d7-4ee6-8b84-ded66f6e842a.jpg)
![Screenshot_20221027_125013_com paauk tipitakapalireader](https://user-images.githubusercontent.com/79864488/198203914-86cbf347-dc0b-476a-a716-6d3363aca74d.jpg)

**Comment by PhiRunh** [comment]
![Uploading Screenshot_20221027_130323_com.paauk.tipitakapalireader.jpg…]()

**Comment by bksubhuti** [comment]
reproduced fixed pushed for next release.
