### ISSUE TITLE
Russian localization 

### ISSUE THREAD

**Issue by o28o** [bksubhuti/tipitaka-pali-reader#136]
Hi. I've noticed that there is no Russian language in options. 

I can do it if you'll show me where is the mapping with English

**Comment by bksubhuti** [comment]
[app_en.txt](https://github.com/bksubhuti/tipitaka-pali-reader/files/10495380/app_en.txt)
Please translate the file given.
Please do not touch the left hand column.
Please only change the content inside the quotes (leave the quotes) on the right .
Here is an example for one file:
  "tipitaka_pali_reader": "Tipitaka Pali Reader",
  "home":                 "Home",
  "bookmark":             "Đánh dấu",
  "recent":               "Gần đây",
  "search":               "Tìm kiếm",
  "updatingStatus":       "Vui lòng chờ trong khi cập nhật dữ liệu.\nCó thể cần đến vài phút.",
  "copyingStatus":        "Vui lòng chờ trong khi sao chép dữ liệu.\nCó thể cần đến vài phút.",
  "settings":             "Cài đặt",
  "dictionary":           "Từ điển",
  "theme":                "Tông màu",
  "darkMode":             "Tông tối",
  "language":             "Ngôn ngữ",

**Comment by o28o** [comment]
Hi.

Thanks. 

Almost done

But I don't know what to choose for 

  "multiViewsMode":        "Multiple Views",
  "numVisibleViews":       "Visible Views"

And 

  "go":                   "Go",
  "toc":                  "TOC",
  "mat":                  "MAT",
  "openingBook":          "Openning Books",



How I can see the use case where these texts are used?

**Comment by o28o** [comment]
Hi.

Thanks. 

Almost done

But I don't know what to choose for 

  "multiViewsMode":        "Multiple Views",
  "numVisibleViews":       "Visible Views"

And 

  "go":                   "Go",
  "toc":                  "TOC",
  "mat":                  "MAT",
  "openingBook":          "Openning Books",



How I can see the use case where these texts are shown?

*addition*

The Pāḷi is claimed to be copyright by VRI, - this one I didn't understand. How Pali can be copyrighted by anyone? What is subject to copyrights in this sentence?

Buddhaghosa or ajahn Jayaysaro youtube." - this one is also not clear is it youtube Channel by someone named after Buddhaghosa?

**Comment by o28o** [comment]
Here is the file with Russian translation.

https://www.dropbox.com/s/di8msfpxq5ltcee/app_ru.txt?dl=0

Except questions above everything should be understandable to russian speaking  users.

**Comment by bksubhuti** [comment]
"go": "Go",  (go to).. running man icon
"toc": "TOC",  (toc table of contents)  it is the help item on the control bar
"mat": "MAT",  (mat.. not sure if it is used.  It is to go from **M**ula to **A**ttha to **T**ika)
"openingBook": "Openning Books",

Did you get everything.. then most should be good.

![image](https://user-images.githubusercontent.com/18184280/214826846-8a2b5229-562e-43cf-8523-ba672566b029.png)


![image](https://user-images.githubusercontent.com/18184280/214826794-e1d74652-83bf-4ae3-82e0-a24974510471.png)


![image](https://user-images.githubusercontent.com/18184280/214826746-74ab10c8-0ddd-426b-a649-44eafe57970e.png)


![image](https://user-images.githubusercontent.com/18184280/214826416-8d521675-1be2-40c2-884d-f0a9323197f1.png)

**Comment by o28o** [comment]
I refreshed the file. you can re-download it.
https://www.dropbox.com/s/di8msfpxq5ltcee/app_ru.txt?dl=0
Buuut  
"multiViewsMode":        "Multiple Views", 
  "numVisibleViews":       "Visible Views" 
}
Still left untouched. 
I see multiple views  on your screenshot but on my phone no such option.
What these two lines are representing? It's easy to translate but need some context.

--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Thursday, 26 January 2023, 06:41PM +07:00 from bksubhuti  ***@***.*** :

**Comment by o28o** [comment]
Hi.

Great that you've already added russian) got the update from Google play today.

Noticed couple of things:

1. In the Language list russian is not from Capital letter like English etc. 
2. Corrected couple of typos in app description, refreshed file https://www.dropbox.com/s/di8msfpxq5ltcee/app_ru.txt?dl=0

**Comment by bksubhuti** [comment]
Please translate following the same model:

{
  "tipitaka_pali_reader": "Tipitaka Pāḷi Reader",
  "home":                 "Главная",
  "bookmark":             "Избранное",
  "recent":               "Недавние",
  "search":               "Поиск",
  "updatingStatus":       "Пожалуйста, дождитесь обновления базы данных\nЭто может занять несколько минут",
  "copyingStatus":        "Пожалуйста, дождитесь копирования базы данных\nЭто может занять несколько минут",
  "settings":             "Настройки",
  "dictionary":           "Словарь",
  "theme":                "Тема",
  "darkMode":             "Страница",
  "language":             "Язык",
  "dictionaries":         "Словари",
  "paliScript":           "Система письма Pāḷi",
  "showAlternatePali":    "Показывать Альтернативный Pāḷi",
  "showPTSPageNumber":    "Показывать номер страницы в PTS",
  "showThaiPageNumber":   "Показывать номер страницы в Тайской версии",
  "showVRIPageNumber":    "Показывать номер страницы в VRI",
  "about":                "О приложении",
  "about_info":           "Это еще одна попытка создать лучшее в истории приложение для чтения Pāḷi текстов . Для этой задачи в качестве нового языка был выбран Flutter и база данных SQLite. Это основной релиз, поэтому приложение должно быть функциональнее предыдущих версий. Версия для ПК ожидается к Январю 2023. В этой версии приложения использован Digital Pāḷi Dictionary, обновление за Сентябрь 2022, созданный Дост. Бодхирасой на условиях лицензирования Creative Commons.  Сайт DPD здесь:  https://digitalpalidictionary.github.io/ .  Мы очень благодарны Достопочтенному за предоставление форматированных таблиц данных и разрешение их использовать. Его проект в процессе активной разработки и мы планируем внедрить обновление словаря отдельно, без необходимости обновлять все приложение. Большая часть кода нашего приложения написана Достопочтенным Пандаззой, я в свою очередь был менеджером проекта и написал некоторые части кода. PEU (Pāḷi English Ultimate) это переведенная версия сокращенного словаря Pāli Myanmar Abhidhān.  Это развивающийся проект, переводы выполняются людьми вручную и с помощью Google.  В нем 168 000 статей, из которых 72 000 переведены вручную.  Он довольно полезен для сложных слов и понятий, которые нет в других словарях.  Вы можете сообщать об ошибках или запрашивать доработки через github https://github.com/bksubhuti/tipitaka-pali-reader/issues , The Pāḷi is claimed to be copyright by VRI, The logo book is modified internet picture, Buddhaghosa or ajahn Jayaysaro youtube.",
  "unable_open_page":     "Невозможно открыть страницу для этого запроса.",
  "enter_note":           "Введите текст заметки",
  "save":                 "Сохранить",
  "cancel":               "Отменить",
  "page":                 "Фон",
  "select_paragraph":     "Выбрать абзац",
  "close":                "Закрыть",
  "paragraph_number":     "Комментарии к абзацу",
  "table_of_contents":    "Содержание",
  "goto":                 "Перейти",
  "paragraph":            "Абзац",
  "go":                   "Перейти",
  "toc":                  "Содержание",
  "mat":                  "Mula, Attha, Tika",
  "font":                 "Шрифт",
  "exact":                "Точное совпадение",
  "prefix":               "Приставка",
  "distance":             "Расстояние между словами",
  "anywhere":             "Любая часть",
  "openingBook":          "Openning Books",
  "animationSpeed":       "Скорость анимации в мс",
  "generalSettings":      "Основные",
  "increaseFontSize":     "Увеличить размер шрифта",
  "decreaseFontSize":     "Уменьшить размер шрифта",
  "openLinkedBook":       "Открыть связанный текст",
  "gotoPageParagraph":    "Перейти на страницу или к абзацу",
  "scriptLanguage":       "Система письменности",
  "dictionaryToClipboard": "Копировать в буфер обращение в словарь",
  "help":                  "Помощь",
  "reportIssue":           "Сообщить о проблеме",
  "areSureDelete":         "Вы уверены, что хотите удалить все записи?",
  "delete":                "Удалить",
  "confirmation":          "Подтверждение",
  "dictionaryHistory":     "История словаря",
  "share":                 "Поделиться",
  "downloadTitle":         "Скачать доп. материалы и словари",
  "filter":                "Фильтр",
  "doYouWantToLeave":      "Вы уверены, что хотите выйти?  Открытые тексты будут закрыты.",
  "yes":                   "Да",
  "no" :                   "Нет",
  "dictionaryFontSize":    "Размер шрифта словаря",
  "panelSize":             "Размер панели",
  "multiViewsMode":        "Multiple Views",
  "numVisibleViews":       "Visible Views",
  "extensions":             "Extensions",
  "quickjump":              "Quick Jump",
  "shareThisNote":          "Share this note",
  "shareAllNotes":          "Share all notes",
  "shareTitle":             "TPR Bookmark and Note",
  "distanceBetweenWords":   "Distance between words",
  "exact":                  "exact",
  "prefix":                 "prefix",  
  "distance":               "distance",
  "anyPart":                "any part",
  "uiFontSize":             "UI fontSize",
  "sortBy":                 "Sort by: ",
  "Time":                   "Time",
  "Alphabetically":         "Alphabetically"
}

**Comment by o28o** [comment]
Hello .

{
"tipitaka_pali_reader": "Tipitaka Pāḷi Reader",
"home": "Главная",
"bookmark": "Избранное",
"recent": "Недавние",
"search": "Поиск",
"updatingStatus": "Пожалуйста, дождитесь обновления базы данных\nЭто может занять несколько минут",
"copyingStatus": "Пожалуйста, дождитесь копирования базы данных\nЭто может занять несколько минут",
"settings": "Настройки",
"dictionary": "Словарь",
"theme": "Тема",
"darkMode": "Страница",
"language": "Язык",
"dictionaries": "Словари",
"paliScript": "Система письма Pāḷi",
"showAlternatePali": "Показывать Альтернативный Pāḷi",
"showPTSPageNumber": "Показывать номер страницы в PTS",
"showThaiPageNumber": "Показывать номер страницы в Тайской версии",
"showVRIPageNumber": "Показывать номер страницы в VRI",
"about": "О приложении",
"about_info": "Это еще одна попытка создать лучшее в истории приложение для чтения Pāḷi текстов . Для этой задачи в качестве нового языка был выбран Flutter и база данных SQLite. Это основной релиз, поэтому приложение должно быть функциональнее предыдущих версий. Версия для ПК ожидается к Январю 2023. В этой версии приложения использован Digital Pāḷi Dictionary, обновление за Сентябрь 2022, созданный Дост. Бодхирасой на условиях лицензирования Creative Commons. Сайт DPD здесь: https://digitalpalidictionary.github.io/ . Мы очень благодарны Достопочтенному за предоставление форматированных таблиц данных и разрешение их использовать. Его проект в процессе активной разработки и мы планируем внедрить обновление словаря отдельно, без необходимости обновлять все приложение. Большая часть кода нашего приложения написана Достопочтенным Пандаззой, я в свою очередь был менеджером проекта и написал некоторые части кода. PEU (Pāḷi English Ultimate) это переведенная версия сокращенного словаря Pāli Myanmar Abhidhān. Это развивающийся проект, переводы выполняются людьми вручную и с помощью Google. В нем 168 000 статей, из которых 72 000 переведены вручную. Он довольно полезен для сложных слов и понятий, которые нет в других словарях. Вы можете сообщать об ошибках или запрашивать доработки через github https://github.com/bksubhuti/tipitaka-pali-reader/issues , The Pāḷi is claimed to be copyright by VRI, The logo book is modified internet picture, Buddhaghosa or ajahn Jayaysaro youtube.",
"unable_open_page": "Невозможно открыть страницу для этого запроса.",
"enter_note": "Введите текст заметки",
"save": "Сохранить",
"cancel": "Отменить",
"page": "Фон",
"select_paragraph": "Выбрать абзац",
"close": "Закрыть",
"paragraph_number": "Комментарии к абзацу",
"table_of_contents": "Содержание",
"goto": "Перейти",
"paragraph": "Абзац",
"go": "Перейти",
"toc": "Содержание",
"mat": "Mula, Attha, Tika",
"font": "Шрифт",
"exact": "Точное совпадение",
"prefix": "Приставка",
"distance": "Расстояние между словами",
"anywhere": "Любая часть",
"openingBook": "Openning Books",
"animationSpeed": "Скорость анимации в мс",
"generalSettings": "Основные",
"increaseFontSize": "Увеличить размер шрифта",
"decreaseFontSize": "Уменьшить размер шрифта",
"openLinkedBook": "Открыть связанный текст",
"gotoPageParagraph": "Перейти на страницу или к абзацу",
"scriptLanguage": "Система письменности",
"dictionaryToClipboard": "Копировать в буфер обращение в словарь",
"help": "Помощь",
"reportIssue": "Сообщить о проблеме",
"areSureDelete": "Вы уверены, что хотите удалить все записи?",
"delete": "Удалить",
"confirmation": "Подтверждение",
"dictionaryHistory": "История словаря",
"share": "Поделиться",
"downloadTitle": "Скачать доп. материалы и словари",
"filter": "Фильтр",
"doYouWantToLeave": "Вы уверены, что хотите выйти? Открытые тексты будут закрыты.",
"yes": "Да",
"no" : "Нет",
"dictionaryFontSize": "Размер шрифта словаря",
"panelSize": "Размер панели",
"multiViewsMode": "Многостраничный режим Views",
"numVisibleViews": "Visible Views",
"extensions": "Расширения",
"quickjump": "Быстрый Переход",
"shareThisNote": "Поделиться записью",
"shareAllNotes": "Поделиться всем",
"shareTitle": "TPR Закладки и Заметки",
"distanceBetweenWords": "Расстояние между словами",
"exact": "строго",
"prefix": "приставка",
"distance": "расстояние",
"anyPart": "любая часть",
"uiFontSize": "Размер Шрифта Интерфейса",
"sortBy": "Сортировать по: ",
"Time": "Времени",
"Alphabetically": "Алфавиту"
}

**Comment by bksubhuti** [comment]
pushed to the Windows app store and Google Play.  I will reopen from time to time.. a few are missing but should be good enough for now.  You can send me your email I can arrange better.  My email with google is the same as my username here
