### ISSUE TITLE
Delete items in history

### ISSUE THREAD

**Issue by Khematto** [bksubhuti/tipitaka-pali-reader#137]
It would be nice to be able to delete items in the history (recent) list. When exploring around the list can get very long.

**Comment by Khematto** [comment]
After reading roadmap point 3 I realize you probably have already thought of this.

**Comment by bksubhuti** [comment]
There is a trash can in the upper right corner.
You can also slide each item to the right.
There should be a video.  Maybe Ill make a new one.

**Comment by Khematto** [comment]
Thanks. I didn't figure out the slide right. In the bookmarks you can hold
and the trash can appears, but in recent you can only slide right. I found
some videos on your YouTube channel but nothing specifically on that.

**Comment by bksubhuti** [comment]
I took a look and it appears that I only made a video for Buddhist Sun.  I'll try to make one soon.  Some new videos are on the tipitaka pali projector channel (which has been renamed).  I will also look into adding a thing called "feature discover".
Some people don't even know about the blue tab on the bottom of the window.

https://pub.dev/packages/feature_discovery
