### ISSUE TITLE
Menus in the  27-1-2023 appimage not rendering correctly

### ISSUE THREAD

**Issue by BBBalls** [bksubhuti/tipitaka-pali-reader#140]
**Describe the bug**
Some of the menus in the settings are rendering as grey fields in the  27-1-2023 appimage. The options can be selected, but are not visible.

**To Reproduce**
Select the Settings gear, then select the General menu.

**Expected behavior**
Visible menus options.

**Screenshots**
![Screenshot from 2023-01-28 17-26-18](https://user-images.githubusercontent.com/90289469/215299358-81c9ac7f-72dc-42e2-b018-289091a5b8c8.png)
![Screenshot from 2023-01-28 17-48-50](https://user-images.githubusercontent.com/90289469/215299868-68243dff-a047-46c7-b59e-aacf5c040f1e.png)
![Screenshot from 2023-01-28 17-50-04](https://user-images.githubusercontent.com/90289469/215299914-1bb5bcd7-d1d7-454f-b82e-b4685cc45760.png)
![Screenshot from 2023-01-28 17-50-12](https://user-images.githubusercontent.com/90289469/215299918-3425828e-b58b-4bd9-8edf-fa5c5be5e6f2.png)
![Screenshot from 2023-01-28 17-26-57](https://user-images.githubusercontent.com/90289469/215299369-cc2f3b84-c811-471b-9c9c-20e55562f6f2.png)

**Desktop (please complete the following information):**
 - OS: Pop_OS 22.04
 - Fuse3 3.10.5-1build1
 - libsqlite3-dev 3.37.2-2ubuntu0.1

**Comment by bksubhuti** [comment]
yes.. I no longer have linux running.  I will see what I can do.. I will upload the old one.  I need a tester person before I go live

**Comment by bksubhuti** [comment]
I think there was a lot more broken with that.  I have uploaded the old appimage for now.  i will try to recompile again.  I did not have a linux to test it on, but now I do.  Good news is it works on mx av linux minus a few missing fonts for mm and some other scripts.
I suspect the newest release of flutter was the problem  I did downgrade after installing, but I think it made a problem.
I usually build on Digtal Ocean 18.04 to avoid problems ... but still have some problems . 
The upgrade to 3.7 flutter was complete so I won't have to downgrade.  I think it will work when I build later this week.

**Comment by BBBalls** [comment]
The menus work with the 3 Feb 2023 appimage build.

**Comment by bksubhuti** [comment]
would you like to test the prerelease flatpak?
https://www.dropbox.com/s/vhtsu3i5og63tkr/TipitakaPaliReader.flatpak?dl=0

flatpak install --reinstall TipitakaPaliReader.flatpak

**Comment by BBBalls** [comment]
I could not install it. Here are the outputs.

`flatpak install --reinstall /TipitakaPaliReader.flatpak`
`error: The application org.americanmonk.TipitakaPaliReader/x86_64/master requires the runtime org.freedesktop.Platform/x86_64/22.08 which was not found`

`flatpak install org.freedesktop.Platform/x86_64/22.08`
`Looking for matches…`
`Skipping: org.freedesktop.Platform/x86_64/22.08 is already installed`

When trying to install the Flatpak there was also a privilege escalation request, which shouldn't be necessary.

**Comment by bksubhuti** [comment]
I don't know.  It works on my machine.  The devs and the docs are not very
friendly.  .  I'm going to probabaly give up.  Sadhu for trying.
