### ISSUE TITLE
Link from Commentary to mula

### ISSUE THREAD

**Issue by Khematto** [bksubhuti/tipitaka-pali-reader#142]
It would be nice to have a function to link back from atthakatha to mula and Tika to atthakatha, as in dpr.  If you get to a place in the atthakatha or Tika by searching you won't have opened the passage in mula first, so you won't have a way to quickly get to mula.

**Comment by bksubhuti** [comment]
Yes.  We need to do that.  We plan to incorporate all features in TPP
The problem is the TPR is organized by pages instead of mm paragraph
numbers.  We will try to figure this out later.  We recommend using 2
different systems for now.  One for basic read and searches(TPR) and TPP
for more heavy searches and going back and forth to commentary .  See road
map on the main GitHub page for TPR

**Comment by Khematto** [comment]
Great. I think organizing by Sutta and paragraph will make it easier to
use. The division into pages is just by accident...

I've noticed one other thing a few times but can't reproduce reliably, so I
haven't posted a report: several times all of my bookmarks have
spontaneously disappeared. I'm using a Samsung A23 with Android 13. I'll
keep trying to notice when it happens.

**Comment by bksubhuti** [comment]
actually the Mula Atth Tika books are all unified by book/mmparagraph number
We will use this system later
The sutta central numbering system is not friendly for commentary lookups.
maybe by design.
Bhante Subhuti

https://AmericanMonk.org
https://withmetta.net

**Comment by Khematto** [comment]
Another couple small issues: Occasionally I find errors in the text,
presumably from the scanning, such as this, from aṭṭhakanipāta,
paṭhamapaṇṇāsakaṃ, mahāvaggo, pahārādasuttaṃ: 'ekaṃ samayaṃ bhagavā
verañjāyaṃ vi harati naḷerupucimandamūle.'
Are you interested in hearing about them?

Also, what is the source of the Suttas with translation in the extended
downloads section? And what is the iit? It would be nice to show
information about such things, maybe even on the various dictionaries...

**Comment by bksubhuti** [comment]
Make a separate issue for all of these mistakes.. titled "Pali mistakes".  It will help remind us.
I think we are not using VRI txt and this is the  issue. but on the bright side we match the actual books better.


> Another couple small issues: Occasionally I find errors in the text, presumably from the scanning, such as this, from aṭṭhakanipāta, paṭhamapaṇṇāsakaṃ, mahāvaggo, pahārādasuttaṃ: 'ekaṃ samayaṃ bhagavā verañjāyaṃ vi harati naḷerupucimandamūle.' Are you interested in hearing about them? Also, what is the source of the Suttas with translation in the extended downloads section? And what is the iit? It would be nice to show information about such things, maybe even on the various dictionaries...

**Comment by bksubhuti** [comment]
can go backwards but only one by one.  Set for release 58.  closed.
