### ISSUE TITLE
dictionary search query not functioning correctly in the 3 Feb 2023 appimage build

### ISSUE THREAD

**Issue by BBBalls** [bksubhuti/tipitaka-pali-reader#143]
**Describe the bug**
When typing a query into the dictionary, search results are not returned 3 Feb 2023 appimage build. When typing the word prediction drop down menu appears, but when a word is selected no results are provided. Pressing enter to get a result does not work either.

Selecting words from a text to get a definition works as expected.

**To Reproduce**
1. Select the dictionary option on the menu bar
2. type in a word into the search field
3. try to select a predicted word
4. or press enter

**Expected behavior**
A result for a dictionary query.

**Screenshots**
[Kooha-2023-02-03-21-52-16.webm](https://user-images.githubusercontent.com/90289469/216752047-abb9d4b5-39d3-417f-934b-e922f1b68fb7.webm)
The above is a video demonstration of what is happening. If it doesn't play, I can share it with you in another way.

**Desktop (please complete the following information):**
 - OS: Pop_OS 22.04
 - TPR 1.7 03-Feb-2023 build

**Comment by bksubhuti** [comment]
yes.. i noticed that too.. for now you have to click on the word, but it is a bug.

**Comment by bksubhuti** [comment]
fix was tested
