### ISSUE TITLE
On Android there is a none functioning dictionary menu option

### ISSUE THREAD

**Issue by BBBalls** [bksubhuti/tipitaka-pali-reader#144]
**Describe the bug**
The dictionary menu option in the three bar menu does not provide a way to query the dictionary. It is just a blank side menu bar.

**To Reproduce**
1. Select the three bar menu button on the top left corner of the app
2. Click on on the dictionary option

**Expected behavior**
The option to enter a dictionary query and view search results.

**Screenshots**
![step1](https://user-images.githubusercontent.com/90289469/216753285-67e852be-d2aa-4e94-90c8-ce7f53102fc0.jpg)

![step2](https://user-images.githubusercontent.com/90289469/216753295-45cf1698-53f5-4cd4-9729-935e6ba3f22f.jpg)

![step3](https://user-images.githubusercontent.com/90289469/216753301-b780e23b-5a81-4d7e-a751-b872c2dadb2c.jpg)

The red square in the screen shots indicate what was selected.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - TPR 2.3.2 [2-Feb-2023 update]

**Comment by bksubhuti** [comment]
reproduced.. will try to fix

**Comment by bksubhuti** [comment]
tested
