### ISSUE TITLE
Not smooth on my iPad.

### ISSUE THREAD

**Issue by Nandavamsa** [bksubhuti/tipitaka-pali-reader#145]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nandavamsa** [comment]
New version of TPR App is not working properly on my iPad Air3. It is very slow to scroll down and up. Touch Responding is also not very well.
App version is 1.7
my iPadOS version is 16.3.1
Thank you _/\_

**Comment by bksubhuti** [comment]
Scrolling is slow by a problem with different sized tiles in a listview.  It is best to use the TOC to jump to the part you want. 
 It is not mean to do scroll many pages all at once (at this stage), but small scrolling should work (like you are reading and scroll inch by inch).. .
  However, perhaps we can make a mobile view available for ipad.  I did see one that was locked up when it was scrolled.  How much free memory do you have.  The ipad that locked up was full.  
  
  are you scrolling on the side bar or just on the main face of the app window

**Comment by Nandavamsa** [comment]
Side bar scrolling down and up Bante🙏🏻
Main face is ok.

**Comment by Nandavamsa** [comment]
Thank you Bante🙏🏻

**Comment by bksubhuti** [comment]
Actually I spoke with the main monk programmer. (I'm just a. Monk manager who can do a little bit of code.)
It can be reproduced in ios16 but not iOS 15 

Can you confirm you are running  ios16

**Comment by Nandavamsa** [comment]
Yes, I am running iPadOS 16 on my iPad Air 3th Gen. 🙏

**Comment by Nandavamsa** [comment]
Thank you for new released version which has bug fixed. Now, running of TPR App is Ok on my iPad.

**Comment by bksubhuti** [comment]
The release was made in haste once we knew the issue.  ios 16x has caused this bug .  We did an emergency release this past sunday before fully ready and forced the mobile app view..  So currently ios has a "fuzzy" always enabled.  There will also be a few seconds delay on the very first typing.  After that it will be quick.  quick jump might work.
The later release to come (already implemented) will have a fuzzy on off button and will work without delay.
