### ISSUE TITLE
Filter button covers search result

### ISSUE THREAD

**Issue by sumbodhi** [bksubhuti/tipitaka-pali-reader#148]
![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/61728359/3b35ed23-eafc-40cd-a9cc-6618e6a4b5cb)

should be below the last card, the list could have padding bottom or a spacer at the end

**Comment by bksubhuti** [comment]
yes.. good idea

**Comment by sumbodhi** [comment]
Fixed by adding padding
![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/61728359/a99fd8cb-0a40-43cc-937d-367b5f2bfd43)
