### ISSUE TITLE
Dictionary should not search number as in leading number of sutta name.

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#153]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bksubhuti** [comment]
fixed.. added check..
      if (_currentlookupWord.isNotEmpty) {
        _lookupDefinition();
      }
