### ISSUE TITLE
After the Sutta button has been clicked, the app should place the cursor in the search box otherwise the user has to make this action.

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#154]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bksubhuti** [comment]
fixed.  closed.
thanks to google bard haha.
