### ISSUE TITLE
Show current position in TOC

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#156]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bksubhuti** [comment]
He wants the scrolling to show the TOC item 

You need to delete the boiler plate stuff and put the description in the body not the subject.
Please edit

**Comment by bksubhuti** [comment]
added by ven pndazza.  Will go in next build release
