### ISSUE TITLE
Go to paragraph function needs to be fined tune

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#157]
**Describe the bug**

**To Reproduce**Steps to reproduce the behavior:
1. Read paragraph 78
2.click on qj walking man icon
3. Click on 'paragraph'
4. Enter 79 then click Go
5. See error: the page displayed is not paragraph 79, need to scroll down a few lines. It's interesting that going back to paragraph 78 works fine although it's more user friendly to show the selected paragraph below the sutta name. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bksubhuti** [comment]
is this a page issue?.. 
if so please close

Currently we bring you to the page, but not  to the paragraph and it is covered in other issues.
If it is difierent you can reopen.
