### ISSUE TITLE
Get in infinite loop with Dictionary on Windows (latest version of TPR)

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#159]
[TPR bug.docx](https://github.com/bksubhuti/tipitaka-pali-reader/files/11555081/TPR.bug.docx)

**Comment by bksubhuti** [comment]
Can you describe more.  ?  What word did you click to cause this.
 Were you able to stop it.  
Were you able to repeat it?

You really need to repeat a big before posting (any software not just mine).

**Comment by sontutmc** [comment]
Dear bhante,

I also uploaded a file with screen shots to recreate the issue. Did it show
up?

**Comment by bksubhuti** [comment]
please do not use docx.
I have fixed a different issue and it seems to be fine now.
