### ISSUE TITLE
Quick Search+Up Down Navigation  keys

### ISSUE THREAD

**Issue by Sugatavihari** [bksubhuti/tipitaka-pali-reader#161]
this  up down Navigate search function still only hve CST4 Windows app(same like windows  word and even when we are in web pages etc this have this Navigation option (ctrl+f) , so Please Add this   'Quick search' option as a seperate function additional to basic search facility   ,  then while  we reading a book then we can quickly   access same dhamma point or point pages up and down the results....
![Screenshot_20230527_135334](https://github.com/bksubhuti/tipitaka-pali-reader/assets/134770450/c193509f-f35d-4741-93b1-7614a56a5499)
![Screenshot_20230527_141341_Xodo](https://github.com/bksubhuti/tipitaka-pali-reader/assets/134770450/bad18bdc-dbae-4a9c-9020-d7466f0be21f)

![Screenshot_20230527_144433_Gallery](https://github.com/bksubhuti/tipitaka-pali-reader/assets/134770450/957ef208-82bd-434b-bcb8-d03783dcc4cb)

**Comment by bksubhuti** [comment]
This is featured with CTRL + F but it was broken with a recent fix on how we make words clickable.
Assigned to Sumbodhi

**Comment by bksubhuti** [comment]
CTRL F is working fine

**Comment by Sugatavihari** [comment]
Yes bhante, will be so much helpful us if this  come with smart devices🙏🙏🙏🙏
