### ISSUE TITLE
Dictionary to Clipboard not working

### ISSUE THREAD

**Issue by bdhrs** [bksubhuti/tipitaka-pali-reader#162]
**Describe the bug**
Dictionary to Clipboard has stopped working after the latest update.

**To Reproduce**
1. Turn on Dictionary to Clipboard in General Settings
2. Click on a word
3. Try paste into a text file, or use DPD hotkey .... nothing happens.

**Expected behavior**
Word clicked should be in the clipboard

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 2.3.2 +38

**Comment by bksubhuti** [comment]
verified on windows release build.  I will look into this.

**Comment by bksubhuti** [comment]
fixed
