### ISSUE TITLE
Quick jump for sn35.28

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#163]
**Describe the bug**
sn35.28 yields a Not found message although sn35.27 or sn35.29 work fine.

**To Reproduce**
![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/111456572/e7d1f22b-59e7-47ec-bdc8-8a4cc2efdf20)e.

**Comment by bksubhuti** [comment]
duplicate..
