### ISSUE TITLE
Reording tabs

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#165]
**Describe the bug**

https://drive.google.com/file/d/16ZtGXqrilyW6UdtwVKCswvgmRwynBLuU/view?usp=drive_link

**Comment by bksubhuti** [comment]
the quick fix is don't do that.  but I've assigned sumbodhi to this.  He works on the tab widget

**Comment by bksubhuti** [comment]
fixed a while ago. by sumbodhi

**Comment by bksubhuti** [comment]
i closed this thinking it was something else.. however.. can look into this for the weekend.. might be related to the other bug of closing tabs

**Comment by bksubhuti** [comment]
can you verify if this is still happening.  Please describe the issue and directly upload the video here to github
