### ISSUE TITLE
Display incorrect commentary

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#168]
**Describe the bug**

https://drive.google.com/file/d/1AA2jcnkEiC7KcVI5gh92-79wQc9asmEE/view?usp=drive_link

**Comment by bksubhuti** [comment]
Please give descriptions with the video as well (in writing).
You can upload vids directly to git hub..  Please do that next time.

seems like the interface is fixed.

![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/18184280/261b526e-761a-4559-8f7f-68ddc0c3d851)
