### ISSUE TITLE
Unable to open commentary for SN35.110 - sn35.118

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#171]
sn35.110 - cannot open its commentary
sn35.118 - cannot open its commentary
sn35.117 - cannot open its commentary
sn35.116 - cannot open its commentary
sn35.115 - cannot open its commentary
sn35.114 - go to the wrong paragraph
sn35.113 - option to open paragraph 115 instead of 113 (the commentary is common for 114-115)

It appears that this whole block of data has some related issues.

**Comment by bksubhuti** [comment]
We appreciate your comments, however, The first two seem fine to me.  
You also do not mention your version number and OS.

Please mention .. more details what page did it bring you to and what page did you expect to be brought to.
Remember that you  are only brought to the page.  Not to the corresponding paragraph.  Please edit your original post to complete the information or post a comment with the complete (not partial) information.

**Comment by sontutmc** [comment]
Sorry for the missing info: Windows 10 TPR version 2.3.3+41. (by the way the problem works fine on Android).
 
Here the video to show how to get there: https://drive.google.com/file/d/1h1VY2ag0STL0d3RgF2EVsZwO6y2F1kW3/view?usp=drive_link

Thanks for a great tool.

**Comment by bksubhuti** [comment]
Please reset your system.  hit the reset button and reboot the app.  Then verify all items.. not with video.. but just type it.
I can load fine
![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/18184280/5d921462-fd82-4d9b-8dfc-e7974fd24d74)

**Comment by sontutmc** [comment]
Fixed in Windows version 2.3.4 +46.
