### ISSUE TITLE
Quickjump for MN

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#185]
**Describe the bug**
Qj starting from MN 21 is not correct. It's off by 10 i.e. qj MN 21 goes to MN 11 etc...

**Desktop (please complete the following information):**
Windows 10, Firefox
TPR 2.3.5 +55

**Comment by bksubhuti** [comment]
Yes.  Looks like all are off by one in the first book after 10

**Comment by bksubhuti** [comment]
post the text file here.

**Comment by sontutmc** [comment]
Additional test results:

MN	QJ test result	QJ to this location
	
10	OK	
	
20	ok	
21	error	11 - Cūḷasīhanāda Sutta  
22	error	12
23	error	13
24	error	14
25	error	15
26	error	16
27	error	17
28	error	18
29	error	19
30	error	20 - Vitakkasaṇṭhāna Sutta 
31	error	21
32	error	22
33	error	23
34	error	24
35	error	25
36	error	26
37	error	27
38	error	28
39	error	29
40	error	30 - Cūḷasāropama Sutta   
41	error	31
42	error	32
43	error	33
44	error	34
45	error	35
46	error	36
47	error	37
48	error	38
49	error	39
50	error	40 - Cūḷa-Assapura Sutta   
51	ok	
60	ok	
70	ok	
80	ok			
90	ok	
100	ok	
110	ok	
120	ok	
130	ok	
140	ok	
150	ok	
151		
152

**Comment by bksubhuti** [comment]
fixed.. will push later
