### ISSUE TITLE
hi,thanks for your work! I can't use the function of search, please note.

### ISSUE THREAD

**Issue by sdpipiwei** [bksubhuti/tipitaka-pali-reader#186]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bksubhuti** [comment]
You will need to give more detail.  Sorry we cannot work with this vague
reporting errors.  Try watching videos on the YouTube channel.  Search for
it on Google

Best wishes
