### ISSUE TITLE
Opened Linked Book for SN35.241 is not correct

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#189]
**Describe the bug**
TPR correctly opens sn35.241 at paragraph 241. However Open Linked Book shows paragraph 243 instead of 241 hence it opens the wrong commentary.

**To Reproduce**
self explanatory.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10
TPR 2.3.5 +56

**Comment by sontutmc** [comment]
Now on TPR Windows version 2.3.6 +57 the error message says "Unable to open page for this page".

**Comment by bksubhuti** [comment]
fixed with new MAT interface.
![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/18184280/cb6da2bf-3f59-4b53-9f2c-8be02526c375)
