### ISSUE TITLE
Whole screen grays out when clicking on a variant

### ISSUE THREAD

**Issue by bdhrs** [bksubhuti/tipitaka-pali-reader#190]
**Describe the bug**
When clicking on a variant reading, the whole screen goes gray if the FIND bar is open.

**To Reproduce**
1. find a variant reading (gray text)
2. open FIND (ctrl f)
3. search for the word next to it
4. click the variant reading
5. whole screen goes gray
I've made a short video replicating the error. 
https://github.com/bksubhuti/tipitaka-pali-reader/assets/64521731/0857b508-3d63-49bf-a267-881d3d0ce8a3

**Expected behavior**
Screen should not go gray when clicking on variants.

**Screenshots**
![Screenshot from 2023-07-28 20-53-16](https://github.com/bksubhuti/tipitaka-pali-reader/assets/64521731/490e0157-0e55-4729-9857-4e833cdb806f)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version:  Linux Mint 19.3 Cinnamon

**Additional context**

**Comment by bksubhuti** [comment]
It is reproducible if you 
1.  turn on variant readings
2. find a gray text alt reading
3. search for that word using ctrl + F.
4. while it is highlighted.. click on it.

**Comment by bksubhuti** [comment]
Fixed by ven pndazza
