### ISSUE TITLE
Search results disappear

### ISSUE THREAD

**Issue by bdhrs** [bksubhuti/tipitaka-pali-reader#191]
**Describe the bug**
Search results disappear after open a text and clicking on a word.

**To Reproduce**
1. search for any word
2. click the search result to open
3. click on any word in the text to open the dictionary
4. click on search icon
5. search results have disappeared

Here's a short video demonstrating the above 
https://github.com/bksubhuti/tipitaka-pali-reader/assets/64521731/6d933ffe-752a-4827-8499-6ef08957a2ff

**Expected behavior**
Search results should stay open.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: Linux Mint 19.3 Cinnamon

**Comment by bksubhuti** [comment]
fixed by ven pndazza
