### ISSUE TITLE
Quickjumps to MN23 and MN24 are not found

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#195]
**Describe the bug**
Quickjumps to MN23 and MN24 give 'Not Found' message.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 2.3.6 +57

**Additional context**

**Comment by bksubhuti** [comment]
it is now fixed.. however, I believe you were the one who made the mn page numbers for me.
It is pushed.. you can try to verify all numbers.. and then look at the file again.

You have to understand that if the page number is below the title... then it is the previous number for that sutta.
I think that was the misunderstanding.  Please recheck all 150 to see if it is okay. 
You can see the changes here.
https://github.com/bksubhuti/tipitaka-pali-reader/commit/4f92049db9d60bb85388d73a480d1478c97eed15
