### ISSUE TITLE
Sutta Search Icon or Tab

### ISSUE THREAD

**Issue by divine1522** [bksubhuti/tipitaka-pali-reader#224]
The Tipitaka Pali Reader App is really helpful and great. 

It would be great if you can add "Sutta Search Icon or Tab in the App.

Thank you
Thakur Krishna Uprety
Nepal

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bksubhuti** [comment]
There is a button on the very first screen.
It is strange you do not see it.  Perhaps you are on a very outdated version.?

**Comment by divine1522** [comment]
Dear Bhante Subhuti,

I found it.
Thank you so much.

Thakur Krishna Uprety
