### ISSUE TITLE
" Double quote breaks DPD recognition

### ISSUE THREAD

**Issue by bdhrs** [bksubhuti/tipitaka-pali-reader#225]
A double (") quote character breaks DPD recognition. 

To reproduce, search for byādhayissasī, (you can find it in sagāthāvaggasaṃyuttapāḷi) and click on the word. It is not recognized because the word in DPD is  byādhayissasīti, so the " character needs to be removed in exactly the same way that the single quote character (') is currently being handled. 

For an example of correct behaviour search for oghamatarī in the same book. oghamatarī’ti is being recognised correctly as 
oghamatari + iti, as the single quote is being removed.

**Comment by bdhrs** [comment]
here's another example, search for **tatthevantaradhāyathā**. The word in DPD is **tatthevantaradhāyathāti** which is not being recognised cos of the "ti

**Comment by bksubhuti** [comment]
okay, that is better.

**Comment by bksubhuti** [comment]
I added the fix.. result is in the dictionary lookup textfield.

![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/18184280/9a2278b0-7efc-4595-823e-d0c79668e6f4)


![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/18184280/813ead58-9ea4-4b82-9857-ee4945811efa)
