### ISSUE TITLE
Non-pāḷi characters rūpante္vava

### ISSUE THREAD

**Issue by bdhrs** [bksubhuti/tipitaka-pali-reader#227]
Search for rūpante္vava. That should be rūpaṃtveva in all cases. 

There are a few more, I will log them as I find them.

**Comment by bksubhuti** [comment]
There is a long term solution to import the vri texts.  However, vri pages and therefore all or most other apps do not match the CST books.  However, TPR does match.  the import is fixable in code, but there is a lot to do.  Someone has been working on this for a while now.  It could be finished by February, but we will need lots of testers to test the integrity.  Could take six months to a year after the code is merged to tpr_downloads

**Comment by bksubhuti** [comment]
rūpante္vava seems to need to change to "rūpanteva"  
Can this be confirmed?

**Comment by bksubhuti** [comment]
Changed to rūpantveva
