### ISSUE TITLE
Wrongly copy Thai words to dictionary. 

### ISSUE THREAD

**Issue by Wisanphuket** [bksubhuti/tipitaka-pali-reader#231]
**Describe the bug**
When click on words. The Thai alphabets order changed. 

**Screenshots**
![1703429055781](https://github.com/bksubhuti/tipitaka-pali-reader/assets/154745236/9a644af5-6f5b-4257-9cb8-a52271ab13e1)
![1703429056044](https://github.com/bksubhuti/tipitaka-pali-reader/assets/154745236/cf19f01c-836c-4343-9f41-67bd9a6a37e3)
![1703429056119](https://github.com/bksubhuti/tipitaka-pali-reader/assets/154745236/1513df0b-c694-4060-ab33-f1098664342b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bksubhuti** [comment]
we had many font issues with international scripts that obviously are not in my daily use cases.. we fixed them.. should come soon .. perhaps this weekend.  Although Google has been slower in approving releases.  We now support current script and roman for dictionary lookups.
