### ISSUE TITLE
Can not launch flatpak application

### ISSUE THREAD

**Issue by Devamitta** [bksubhuti/tipitaka-pali-reader#232]
**Describe the bug**
I installed TPR using Flatpak on Linux, but I am unable to launch it. Could it be because I am missing some dependencies?

**To Reproduce**
1. opened terminal
2. `flatpak install org.americanmonk.TipitakaPaliReader`
3. Open start menu
4. Click Tipitaka Pali Reader
5. I briefly saw a new window, but it disappeared.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2 Cinnamon 5.8.4

**Comment by bksubhuti** [comment]
Do you see a menu for tipitaka pali reader?

**Comment by bksubhuti** [comment]
I am on 21.2 mint as well. and it works fine on my machine as well as other mint users.
One monk said he launched it a second time and it worked.. try..

**Comment by bksubhuti** [comment]
If it does not work .. you can try installing libsqlite3-dev

If that does not work.. Please do step by step so I know..

Try installing these app..
sudo apt-get install libgtk-3-0 libblkid1 liblzma5

and if that does not work.. try the developer apps..
.
sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev


let me know why which step helped.
Sounds like sqlite will fix it.. but it should be included in the flatpak framework.. but maybe they don't have the dev version..

**Comment by Devamitta** [comment]
Thank you Bhante for your attention.


> One monk said he launched it a second time and it worked.. try.

tried many times

> If it does not work .. you can try installing
> `sudo apt install libsqlite3-dev`

libsqlite3-dev is already the newest version (3.37.2-2ubuntu0.1).

> `sudo apt-get install libgtk-3-0 libblkid1 liblzma5`

libblkid1 is already the newest version (2.37.2-4ubuntu3).
liblzma5 is already the newest version (5.2.5-2ubuntu1).
libgtk-3-0 is already the newest version (3.24.33-1ubuntu2).


> `sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev`

the installation has been succeeded, and after using this command again the result is:

`liblzma-dev is already the newest version (5.2.5-2ubuntu1).`
`pkg-config is already the newest version (0.29.2-1ubuntu3).`
`clang is already the newest version (1:14.0-55~exp2).`
`ninja-build is already the newest version (1.10.1-1).`
`cmake is already the newest version (3.22.1-1ubuntu1.22.04.1).`
`git is already the newest version (1:2.34.1-1ubuntu1.10).`
`libgtk-3-dev is already the newest version (3.24.33-1ubuntu2).`
`libstdc++-12-dev is already the newest version (12.3.0-1ubuntu1~22.04).`

---

even after rebooting the same issue - app tries to open, I see window for a sec and then it is disappeared

when I try to lunch it is the terminal, the result is:

---

`Gtk-Message: 09:59:20.838: Failed to load module "xapp-gtk3-module"`

`(tipitaka_pali_reader:2): Gdk-CRITICAL **: 09:59:20.864: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed`

when I try to install 


❯ sudo apt-get install libxapp-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libgnomekbd-dev libxkbfile-dev libxklavier-dev
The following NEW packages will be installed:
  libgnomekbd-dev libxapp-dev libxkbfile-dev libxklavier-dev
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
...
Unpacking libxapp-dev (2.6.1+victoria) ...
Setting up libxklavier-dev:amd64 (5.4-4build2) ...
Setting up libgnomekbd-dev:amd64 (3.26.1-2) ...
Setting up libxkbfile-dev:amd64 (1:1.1.0-1build3) ...
Setting up libxapp-dev (2.6.1+victoria) ...

gir1.2-xapp-1.0 is already the newest version (2.6.1+victoria).

❯sudo apt-get install xapp

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xapp : Depends: libxapp1 (= 2.2.8-1) but 2.6.1+victoria is to be installed
E: Unable to correct problems, you have held broken packages.

❯ sudo apt-get install libxapp1=2.2.8-1 --allow-downgrades
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mintsources : Depends: mint-common (>= 2) but it is not going to be installed
               Depends: gir1.2-xapp-1.0 but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

❯ sudo apt-get install mint-common gir1.2-xapp-1.0        
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mint-common is already the newest version (2.3.0).
gir1.2-xapp-1.0 is already the newest version (2.6.1+victoria).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

so it is like a loop =)

**Comment by bksubhuti** [comment]
So did it work ?
I didn't understand your response.

**Comment by Devamitta** [comment]
No Bhante, the error is:

Gtk-Message: 11:45:37.674: Failed to load module "xapp-gtk3-module"

(tipitaka_pali_reader:2): Gdk-CRITICAL **: 11:45:37.700: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

and the window is appearing for a sec

**Comment by bksubhuti** [comment]
You might want to look at the directory .var/app/org.americanmonk/TipitakaPaliReader/data/tipitaka_pali_reader
try deleting that directory.. or delete with the flatpak command to remove all data.
https://forums.linuxmint.com/viewtopic.php?t=395080#:~:text=flatpak%20uninstall%20%2D%2Dunused%20%2D%2D,%22%20with%20actual%20package%20IDs).

![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/18184280/4d0d5dee-a353-4835-b5de-493dbfae0a83)

**Comment by bksubhuti** [comment]
a new version of flatpak will be released soon.  Perhaps there was something corrupted in the db.  We can try again.

**Comment by Devamitta** [comment]
Bhante, now I am trying just to launch latest Appimage, and have an error:

`zsh: segmentation fault (core dumped)  ./tipitaka_pali_reader.AppImage`

what it can be?

**Comment by Devamitta** [comment]
on another Linux Mint PC error is a bit different:

`Gtk-Message: 21:04:38.924: Failed to load module "xapp-gtk3-module"`
`(tipitaka_pali_reader:2): Gdk-CRITICAL **: 21:04:39.279: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
malloc(): unsorted double linked list corrupted`

**Comment by bksubhuti** [comment]
These errors are normal and don't matter.

We will make another release .. maybe this weekend.. then need to get approved.  Perhaps there was something wrong with the build.

**Comment by bksubhuti** [comment]
Did you ever get it to work?
We have an appimage that works (I forgot to tell you).
I will be hopefully making a new flatpak this weekend.  We are now "verified".  That just means our website that we registered with is actually our website and now has a key for them.

**Comment by bksubhuti** [comment]
flatpak has been very disappointing.  It seems to not work on my machine too using 24.04 ubuntu.  I have a message out to a person who helped me build it.  I recommend using an appimage and then making a desktop for now.

**Comment by Devamitta** [comment]
Yes the AppImage is working well.

**Comment by bksubhuti** [comment]
okay.. we will see soon enough.. I might have to downgrade to mint 22.04 this weekend because of trouble.

**Comment by bksubhuti** [comment]
if you want , you can try the new flatpak.. also have appimage released.

**Comment by Devamitta** [comment]
Yes , working well. I think we can close the issue, Bhante.

**Comment by bksubhuti** [comment]
Great!  We are also verified publishers.  So that will help with the new mint.  I had trouble with 24.04 so I won't be upgrading for a while.  There really is no need anyway.
