### ISSUE TITLE
can not search for the page number

### ISSUE THREAD

**Issue by sdpipiwei** [bksubhuti/tipitaka-pali-reader#242]
**Describe the bug**
when reading the text, want to go to some page , for example ,i want to page 67, i have no means, if i can search "67", then i can go to the page immediately.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bksubhuti** [comment]
Please watch videos on the youtube menu .

![image](https://github.com/bksubhuti/tipitaka-pali-reader/assets/18184280/9bee2c18-03c5-4aaa-8701-fd866fbbff6a)
