### ISSUE TITLE
Search in current (Ctrl F) move cursor into search box for instant typing

### ISSUE THREAD

**Issue by bdhrs** [bksubhuti/tipitaka-pali-reader#246]
When using Ctrl-F to search within a text, currently one needs to go the mouse, move to the search box, and then start typing. 

I propose the cursor move automatically to the search box, so one can Ctrl-F and start typing immediately. 

This would be really useful, especially when doing hundreds of searches.

**Comment by bksubhuti** [comment]
If I remember there were issues with this.. but maybe only for the mobile and popup keyboards.
I think just setting to request focus (if IsDesktop) should work.

**Comment by bksubhuti** [comment]
fixed and tested
