### ISSUE TITLE
Some extra Pali texts

### ISSUE THREAD

**Issue by khemanando** [bksubhuti/tipitaka-pali-reader#265]
Hi, I think it would be good, if app would have some extra Pali texts from here https://gretil.sub.uni-goettingen.de/gretil.html#Pali

**Comment by bksubhuti** [comment]
we have the extra pali texts from the CST (same as vri texts website).  We are working on it.
You can play with this on the extensions screen found in settings/tools/extensions
Make sure you wait until you get the original list displayed again before closing.

We might include other editions.  It is on the list.
I don't see us ever  supporting anything but  pali as religious texts

issue closed.  Different editions are already scheduled but far away..
