### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by Scala2024** [bksubhuti/tipitaka-pali-reader#267]
1. Typo error:

In the Sutta button,   "Openning Books" (with double n)

**Comment by bksubhuti** [comment]
Can you provide a screenshot.  While the code is spelled wrong, I don't see any button you are talking about that says "openning books".

**Comment by Scala2024** [comment]
![WhatsApp Image 2024-10-13 at 5 05 07 PM](https://github.com/user-attachments/assets/5befa2b9-2b1b-4ca3-a008-a6bec43cec69)

**Comment by Scala2024** [comment]
After I click the sutta round button, then the small icon  (on the right top) that show the no of books opened .

**Comment by bksubhuti** [comment]
okay.. i found it.
you are clicking on the number on the top right corner.
I have no idea why you described it as a sutta button.

**Comment by bksubhuti** [comment]
https://github.com/bksubhuti/tipitaka-pali-reader/commit/3f375bf82f947182cd9bd1af2a019c441a53c947
