### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by sontutmc** [bksubhuti/tipitaka-pali-reader#268]
**Describe the bug**
Typo with the word extensions

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/7f27548e-5009-4117-80e6-bc18fc6f0de0)

**Desktop (please complete the following information):**
 - OS: Windows and Android

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bksubhuti** [comment]
fixed for next release
