### ISSUE TITLE
Can't incorporate latest DPD version, and the old version disappears from my TPR 

### ISSUE THREAD

**Issue by Grateful123** [bksubhuti/tipitaka-pali-reader#271]
Sorry, I don't know whether I'm at the right place to report this matter.  But please forgive me if I'm not.

I have installed TPR in my laptop about a year ago, it works well - I find the DPD very powerful and helpful, for it can break down the Pali words into prefix, root and suffix.  But, after I have tried to download the latest version DPD beta 23.6 MB, and DPD October 2024 release, the DPD now disappears from my dictionary.  I wonder if it is due to the new version cannot be fully downloaded into my laptop, (because I find the insertion stopped at  4413000 lines and cannot move on.

Would it be possible the older version be put up for downloading again.  Or else, how can I resolve this matter. My macOS Monterey 12.2.1.

Thank you very much for your kind help in advance!

**Comment by bksubhuti** [comment]
you have to write your version number (of tpr) when you lodge a bug.
But it sounds like you don't have the latest version of TPR and you are trying to install extensions meant for that version.
Please do so and if everything works.. then  please report back here and close the issue.

**Comment by Grateful123** [comment]
Thank you so much Bhante. You are right.  It is I who forgot to update my TPR app to the latest version before I downloaded the extension. The issue is fully resolved now. Many thanks for your kind help. 🙏🙏

**Comment by bksubhuti** [comment]
I'm glad to hear that.  
closed.
